variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

image: docker:stable
services:
  - docker:dind

stages:
  - build
  - test

before_script:
  - apk update
  - apk add bash

build_rails_app:
  stage: build
  artifacts:
    paths:
      - rails_neutrino_app
      - tmp
  script:
    - bash ci-build.sh

test_rails_sqlite:
  stage: test
  script:
    - bash ci-test.sh 'rails_neutrino_test_sqlite'
