variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

image: docker:stable
services:
  - docker:dind

build_rails_app:
  stage: build
  script:
    - apk update
    - apk add bash
    - apk add docker-compose
    - bash ci.sh
