variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

image: docker:stable
services:
  - docker:dind

build_rails_app:
  stage: build
  before_script:
    - apk update
    - apk add bash
  script:
    - bash ci.sh
