#!/bin/bash

# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
# Without this specification, the CI status will provide a false sense of security by showing builds
# as succeeding in spite of errors or failures.
set -euo pipefail

# This script ensures that all files in the app within the Docker image are owned by the user winner.
# This is necessary for the continuous integration setup,
# where Docker does weird things.

DIR_MAIN='/home/winner/myapp'

chown -R winner:winner $DIR_MAIN

su -c $DIR_MAIN/test_app_internal winner
