#!/bin/bash

# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
# Without this specification, the CI status will provide a false sense of security by showing builds
# as succeeding in spite of errors or failures.
set -euo pipefail

echo '---------------------'
echo 'yarn install --silent'
yarn install --silent

echo '----------------------'
echo 'bundle install --quiet'
bundle install --quiet

# Skip the migration until docker/migrate is provided
if [ -f docker/migrate ]; then
  echo '---------------------------'
  echo 'bundle exec rake db:migrate'
  bundle exec rake db:migrate
fi
  
# Skip the testing until docker/test is provided
if [ -f docker/test ]; then
  echo '---------------------'
  echo 'bundle exec rake test'
  bundle exec rake test
fi

# Skip RuboCop until docker/cop-auto is provided
if [ -f docker/cop-auto ]; then
  echo '----------------------'
  echo 'bundle exec rubocop -D'
  bundle exec rubocop -D
fi

# Skip Rails Best Practices until docker/rbp is provided
if [ -f docker/rbp ]; then
  echo '----------------------------------'
  echo 'bundle exec rails_best_practices .'
  bundle exec rails_best_practices .
fi

# Skip Brakeman until bin/brakeman is provided
if [ -f bin/brakeman ]; then
  bin/brakeman
fi

# Skip bundler-audit until bin/audit is provided
if [ -f bin/audit ]; then
  bin/audit
fi

# Skip bundler-outdated until docker/bundle-outdated is provided
if [ -f docker/bundle_outdated ]; then
  bin/bundle_outdated
fi

# Skip tree until docker/tree is provided
if [ -f docker/tree ]; then
  bin/tree
fi
