#!/bin/bash

# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
# Without this specification, the CI status will provide a false sense of security by showing builds
# as succeeding in spite of errors or failures.
set -eo pipefail

# Checks the quality of Rails code, not recommended for legacy apps
echo '----------------------------------'
echo 'bundle exec rails_best_practices .'
docker/run bundle exec rails_best_practices .
