#!/bin/bash
set +e

APP_PATH='/home/winner/myapp'

# Set permissions
# NOTE: Skipping this step in the GitLab CI setup results in permission issues
chown_dir () {
  DIR_TO_CHOWN=$1
  echo '--------------------------------------------------------------'
  echo "mkdir -p $DIR_TO_CHOWN && chown -R winner:winner $DIR_TO_CHOWN"
  docker-compose run --rm -u root web bash -c "mkdir -p $DIR_TO_CHOWN && chown -R winner:winner $DIR_TO_CHOWN"
}

chown_dir "$APP_PATH"

# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
# Without this specification, the CI status will provide a false sense of security by showing builds
# as succeeding in spite of errors or failures.
set -eo pipefail

docker/gem_install_bundler

echo '-------------------'
echo 'BEGIN: yarn install'
echo '-------------------'
docker/run yarn install
echo '-----------------'
echo 'END: yarn install'
echo '-----------------'

echo '---------------------'
echo 'BEGIN: bundle install'
echo '---------------------'
docker/run bundle install
echo '-------------------'
echo 'END: bundle install'
echo '-------------------'
