#!/bin/bash

# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
# Without this specification, the CI status will provide a false sense of security by showing builds
# as succeeding in spite of errors or failures.
set -eo pipefail

# This script runs the entire test suite AND logs the screen output.

DATE=`date +%Y%m%d-%H%M%S-%3N`
docker/test-log 2>&1 | tee log/test-$DATE.log
