#!/bin/bash

# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
# Without this specification, the CI status will provide a false sense of security by showing builds
# as succeeding in spite of errors or failures.
set -eo pipefail

# BEGIN: PostgreSQL setup
#POSTGRES#exec_pg_setup () {
  #POSTGRES#FILENAME=$1
  #POSTGRES#if [[ ! -f $FILENAME ]]
  #POSTGRES#then
    #POSTGRES#docker/pg_setup_1
  #POSTGRES#fi
#POSTGRES#}

#POSTGRES#exec_pg_setup 'config/database.yml'
#POSTGRES#exec_pg_setup '.env-docker/development/database'
# END: PostgreSQL setup

docker/create_dockerfile
docker/compose_build

#GEM_INSTALL_BUNDLER docker/gem_install_bundler

#BUNDLE_INSTALL docker/bundle_install

# The "bundle exec rake db:create db:migrate db:test:prepare" command
# is needed to setup up the PostgreSQL database.
#POSTGRES#docker/db_setup

#DATABASE_MIGRATE docker/migrate

#TEST_APP docker/test

# docker/outline

# docker/test_code
