name: Build

on:
  pull_request:
  push:
  schedule:
    - cron: '25 09 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        DATABASE: ['sq', 'pg']
        LENGTH: ['long']
        PARALLEL_TASK: ['audit', 'brakeman', 'cop', 'railroady', 'rails-erd', 'rbp', 'test-log']

    env:
      DATABASE_CI: ${{ matrix.DATABASE }}
      LENGTH_CI: ${{ matrix.LENGTH }}
      PARALLEL_TASK_CI: ${{ matrix.PARALLEL_TASK }}

    steps:
      - uses: actions/checkout@v3

      - name: Initialize the build setup
        run: bin/start-$LENGTH_CI-host

      - name: Build the app in Docker
        run: bin/start-build

      - name: Copying the app from Docker to the host environment
        run: bin/docker-to-host

      - name: Setting up the app with docker-compose
        run: bin/docker-app-setup

      - name: Other tasks in the app with docker-compose
        run: bin/docker-app-task
