name: Build

on:
  pull_request:
  push:
  schedule:
    - cron: '25 09 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        DATABASE: ['sq', 'pg']

    steps:
      - uses: actions/checkout@v3

      - name: Build the Rails app
        run: bash main.sh
