name: Build

on:
  pull_request:
  push:
  schedule:
    - cron: '25 09 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        DATABASE: ['sq', 'pg']
        LENGTH: ['long']

    env:
      DATABASE_CI: ${{ matrix.DATABASE }}
      LENGTH_CI: ${{ matrix.LENGTH }}

    steps:
      - uses: actions/checkout@v3

      - name: Initialize the build setup
        run: bin/start-$LENGTH_CI-host

      - name: Build the app in Docker
        run: bin/start-build

      - name: Copying the app from Docker to the host environment
        run: bin/docker-to-host
