#!/bin/bash

# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
# Without this specification, the CI status will provide a false sense of security by showing builds
# as succeeding in spite of errors or failures.
set -eo pipefail

docker/replace_sif "# gem 'sandi_meter'" "gem 'sandi_meter'" 'Gemfile'

echo '----------------------'
echo 'bundle install --quiet'
bundle install --quiet

# Checks for compliance with Sandi Metz' four rules
echo '-----------------------'
echo 'bundle exec sandi_meter'
bundle exec sandi_meter

docker/replace_sif "gem 'sandi_meter'" "# gem 'sandi_meter'" 'Gemfile'

echo '----------------------'
echo 'bundle install --quiet'
bundle install --quiet
